### ISSUE TITLE
About demo

### ISSUE THREAD

**Issue by YuehengLuo** [naver/posescript#11]
Hello! Thanks for your work. I have a problem with the Text-conditioned Generative Model for 3D Human Poses. I successfully ran your demo by running streamlit run generative/demo_generative.py -- --model_paths </path/to/model.pth> and got the following result:
![image](https://github.com/naver/posescript/assets/70797669/e574f5aa-8639-4233-ae31-547490cc79fc)
The Generated poses here seem to be based on the default Annotated text, and I'm wondering how I can enter the text myself and get a sample.

**Comment by g-delmas** [comment]
Hi!
The text area (with the grey background) is initialized with the annotated text, but normally, you can edit it -- this is the actual input to the model. The annotated text above and the pose on the left are only displayed for reference.

**Comment by YuehengLuo** [comment]
Thanks for your quick response. I know I can change the Pose description, but it only changes when I press analysis. For example，
![image](https://github.com/naver/posescript/assets/70797669/b86f9819-0b25-4b0b-9b77-29344edb4d58)
Now the Annotated text is different from the Pose description, the green part is generated by the Annotated text but the rest is generated by the Pose description, am I understanding this correctly?

**Comment by g-delmas** [comment]
For the demo to take into account the text modification (ie. register a change), you need either to press ctrl+enter after editing, or to click somewhere else on the page (not necessarily on a button, just on the side is fine). My guess is that this is why you only saw the results when clicking on "analysis". Can you try modifying the text as you like, then pressing ctrl+enter or clicking somewhere on the page?

Besides, please note that the "analysis" checkbox makes it possible to assess a bit the internal (qualitative) quality of the VAE. In particular, the green pose is the result of the encoding-decoding of the target pose -- the text is not involved there. It just tells you how good the pose encoder and pose decoder of the VAE are; it illustrates the reconstruction term of the training objective, in some sense. I'm sorry, I am just noticing that the title "generated poses" can be a bit misleading in this case.
The other poses (red & grey) do take the text input as account. The text is encoded as a distribution, from which the pose is sampled and decoded. The red pose is the mean of the distribution, while the grey poses are sampled are random within the distribution.

**Comment by YuehengLuo** [comment]
Thanks for the explanation! I'll try it later.
