### ISSUE TITLE
About line 35 in script_generative_modifier.sh

### ISSUE THREAD

**Issue by minjung98** [naver/posescript#17]
Hello, I apologize for the continued questions. Thank you very much for your prompt and kind responses. This question is related to an error when running the posescript/src/text2pose/generative_modifier/script_generative_modifier.sh file in finetune mode. Here is the traceback:
```
Traceback (most recent call last):
File "generative_modifier/train_generative_modifier.py", line 213, in <module>
    ModifierGenerationTrainer(args, path_to_pretrained_pose_encoder_ckpt)()
File "/home/minjung/posescript/src/text2pose/trainer.py", line 291, in call
    self.start_or_resume_training()
File "/home/minjung/posescript/src/text2pose/trainer.py", line 131, in start_or_resume_training
    pretrained_path = (config.shortname_2_model_path[self.args.pretrained]).format(seed=self.args.seed)
KeyError: 'modgen_CAtransfPFAHPP_dataPFA'

```

It seems to me that in line 35 of the script_generative_modifier.sh file, the part pretrained="modgen_CAtransfPFAHPP_dataPFA"  should be changed to pretrained="modgen_CAtransfPFAHPP_dataPFA**ftPFH**". When you showed an example of how to write the shortname_2_model_path.txt file, it was written as follows:

```
ret_distilbert_dataPSA2ftPSH2    <GENERAL_EXP_OUTPUT_DIR>/ret_distilbert_dataPSA2ftPSH2/seed1/checkpoint_best.pth
modret_distilbert_dataPFAftPFH    <GENERAL_EXP_OUTPUT_DIR>/modret_distilbert_dataPFAftPFH/seed1/checkpoint_best.pth
gen_distilbert_dataPSA2ftPSH2    <GENERAL_EXP_OUTPUT_DIR>/gen_distilbert_dataPSA2ftPSH2/seed1/checkpoint_best.pth
b_gen_distilbert_dataPFAftPFH    <GENERAL_EXP_OUTPUT_DIR>/b_gen_distilbert_dataPFAftPFH/seed1/checkpoint_best.pth
capgen_CAtransfPSA2H2_dataPSA2ftPSH2    <GENERAL_EXP_OUTPUT_DIR>/capgen_CAtransfPSA2H2_dataPSA2ftPSH2/seed1/checkpoint_best.pth
modgen_CAtransfPFAHPP_dataPFAftPFH    <GENERAL_EXP_OUTPUT_DIR>/modgen_CAtransfPFAHPP_dataPFAftPFH/seed1/checkpoint_best.pth
```

Is there a specific reason you initially set pretrained="modgen_CAtransfPFAHPP_dataPFA" in line 35 of the script_generative_modifier.sh file? Yesterday, I modified it to pretrained="modgen_CAtransfPFAHPP_dataPFAftPFH" and ran it, and it seemed to execute without any errors.

**Comment by g-delmas** [comment]
Thank you for your question. I realize the READMEs are not clear enough regarding the finetuning step.

In the script, `pretrained` defines the nickname of the pretrained model. The mapping between nicknames and actual model paths is given in *shortname_2_model_path.txt*. This means that if you train a model and intend to use its weights to train another, you should write its path in  *shortname_2_model_path.txt*, give it a nickname, and write this nickname in front of `pretrained=` in the script.

The reason why you had this bug is that you first need to create a new entry for `modgen_CAtransfPFAHPP_dataPFA` in *shortname_2_model_path.txt*. The reason why it worked by adding 'ftPFH' is because 'modgen_CAtransfPFAHPP_dataPFAftPFH' was already defined there; however it links to the model you downloaded (already finetuned), not the one you trained personally.

Does it make sense? I will update the READMEs to clarify this aspect.

**Comment by minjung98** [comment]
So, does that mean I have to manually write the path of the model I saved after pretraining and finetuning into shortname_2_model_path.txt?

**Comment by g-delmas** [comment]
Yes, for every model that will be used by another (either as pretraining or for evaluation).

You can make this automatic by:
1. specifying the nickname of the model in argument of the script; eg. at current line 48 of *posescript/src/text2pose/generative_modifier/script_generative_modifier.sh*, create a new line with: `nickname=$4` and you'll just have to write whatever you like when calling the script; or predefine nicknames at current lines 51:  `nickname='modgen_CAtransfPFAHPP_dataPFA'` and 61: `nickname='modgen_CAtransfPFAHPP_dataPFAftPFH'`
2. passing `$nickname` as input to the python script; eg. at current lines 57 and 69, append `--nickname $nickname`
3. creating an entry in *posescript/src/text2pose/option.py* for the new argument; eg. at current line 89 add a new line for `parser.add_argument('--nickname', type=str, help='nickname of the experiment')`
4. at the end of *posescript/src/text2pose/trainer.py*, add the following:
```python
with open("shortname_2_model_path.txt", "a") as f:
    f.write(f"{self.args.nickname}    {os.path.join(self.args.output_dir, 'checkpoint_best.pth'))}\n")
```

Disclaimer: I have not tested this.

**Comment by minjung98** [comment]
Now I understand. I will also try the automation method you suggested. Thank you for your response.
