### ISSUE TITLE
Difference between pretrain and finetune phase.

### ISSUE THREAD

**Issue by minjung98** [naver/posescript#19]
I would like to know about the purposes of pretraining and fine-tuning related to the generative_modifier task. 
As far as I know, the purpose of pretraining is to allow the model to acquire general knowledge about the relevant field, while fine-tuning is intended to enable the model to acquire detailed knowledge for a specific task. 
Could you please explain the differences in the datasets and purposes for pretraining and fine-tuning when running script_generative_modifier.sh? Thank you for always providing thorough answers.

**Comment by g-delmas** [comment]
Hello!

Our pretraining stage makes use of annotations obtained automatically thanks to the pipeline described [here](https://github.com/naver/posescript/blob/main/src/text2pose/posefix/README.md#page_with_curl-generate-automatic-modifiers), while our finetuning stage uses human-written texts. While the task is the same in both cases, there is a slight but important domain gap, and a large difference of scale (about 100k automatic annotations, against 6k human-written annotations). 

The first stage aims to give the model basic knowledge about pose configurations, and typical limb-level differences.  The second stage helps to improve the quality of the produced texts, making them more human-like, more concise, and prone to output higher-level semantics. It basically leverage prior knowledge from synthetic data and performs "domain adaptation".

In general, we noticed that human-written texts were more useful at training time when starting from a model already a bit knowledgeable. The finetuning stage could use both automatic & human-written texts at once, in a balanced way.

**Comment by minjung98** [comment]
Reading your response was incredibly helpful. Thank you so much for always taking the time to provide such thoughtful answers. Every time, I learn something new and gain deeper insights from your explanations. Your detailed explanation this time has truly enhanced my understanding. I sincerely appreciate it. I look forward to learning more from you in the future and will continue to support your efforts.
