### ISSUE TITLE
Question on text_decoders.py 

### ISSUE THREAD

**Issue by minjung98** [naver/posescript#22]
I have a question about a piece of code I'm reviewing.

`if caption_lengths[0].item() < self.min_decoded_length:`
    `pred[:, -1, self.tokenizer.eos_token_id] = 0`

I understand this code to mean that it prevents the selection of the EOS (end-of-sequence) token until the caption reaches the desired length. However, I wonder why it only compares the caption length of the first batch(caption_lengths[0]) with self.min_decoded_length and then applies this treatment to all pred if the first batch's caption length is shorter than self.min_decoded_length.

Is there an intended element of randomness here, or is there another reason for this approach?

Thank you.

**Comment by g-delmas** [comment]
Hello!

All texts in the batch are processed in parallel, and get one new token at each iteration(*). While the minimum number of token is not reached, all texts will get +1 token, and thus have the same length. So we can use the length of the first element to detect the length of all the texts in the batch. Once we pass the minimum number of iteration, texts are authorized to come to an end, and indeed, the length of the first caption is not informative about the length of other captions. But then the length of the first caption is higher than the minimum number of token anyway, the condition is not fulfilled, and thus the code below is not reached.

If I am not mistaken, this code can produce a batch of texts of different lengths.

(*) Unless they already produced the EOS token, in which case the proposed new token is ignored; but this happens after we passed the minimum number of iteration.

**Comment by minjung98** [comment]
Thank you for your answer. I think I was confused about the captions_lengths in the forward part. Thanks to your explanation, I now fully understand, and I also have a clearer understanding of the generate_greedy function.
