### ISSUE TITLE
Question on "posescript_auto_100k.json".

### ISSUE THREAD

**Issue by XIDIANPQZ** [naver/posescript#25]
Hello,

I noticed that the file "posescript_auto_100k.json" contains three descriptions for each pose, whereas the generated description from "posescript/captioning.py" provides only one. Could you clarify if these three descriptions in the JSON file are from different versions or if they result from a different process?

Thank you!

**Comment by g-delmas** [comment]
Hello,

You are right, these three descriptions were obtained by running the script thrice with different arguments.
For details, you can check the table in section "*To generate caption versions similar to the latest version of the dataset (posescript-A2)*", on [this page](https://github.com/naver/posescript/tree/main/src/text2pose/posescript)!

**Comment by g-delmas** [comment]
Please note that if you run the same script (with the same arguments) several times, you would also obtain different captions for each pose (because of some randomization, at several steps).

**Comment by XIDIANPQZ** [comment]
Thank you

**Comment by mkstmyk** [comment]
I'm also interested in the mechanism for randomizing the captioning. In my case, to process a pose sequence, I'd like to get temporally consistent captions. To do so, in addition to disable --random_skip, I'm modifying captioning.py to avoid such randomization such as random.choice. Are there any other points to be modified? Thank you in advance!

**Comment by g-delmas** [comment]
Here are the other elements involving randomization, aside from `random.choice`, that I currently remember of:

* https://github.com/naver/posescript/blob/f5282b1115ab09a077ba50a04b230a939306c604/src/text2pose/posescript/captioning.py#L286-L290

* https://github.com/naver/posescript/blob/f5282b1115ab09a077ba50a04b230a939306c604/src/text2pose/posescript/captioning.py#L769
https://github.com/naver/posescript/blob/f5282b1115ab09a077ba50a04b230a939306c604/src/text2pose/posescript/captioning.py#L803
https://github.com/naver/posescript/blob/f5282b1115ab09a077ba50a04b230a939306c604/src/text2pose/posescript/utils.py#L332
You can either deactivate calls to `random.random()`, or set `PROP_AGGREGATION_HAPPENS` to 2 in file *captioning_data.py*.

* This step involves randomness, but if you remove it, you will end up with "unbalanced" captions (eg. always comparing the left side to the right side, and never the other way around); this also has impacts on the possible results of the aggregation rules happening afterwards.
https://github.com/naver/posescript/blob/f5282b1115ab09a077ba50a04b230a939306c604/src/text2pose/posescript/captioning.py#L858

* You can probably get rid of this: https://github.com/naver/posescript/blob/f5282b1115ab09a077ba50a04b230a939306c604/src/text2pose/posescript/captioning.py#L866

* If you want to track changes in the captions over time, you may want to avoid changes in general formulation too, coming in part from the aggregation rules. Not to apply any aggregation rule, you can specify `--simplified_captions` as argument of the process.

* Note that there are several `random.shuffle` in this function as well (aggregation rule): https://github.com/naver/posescript/blob/f5282b1115ab09a077ba50a04b230a939306c604/src/text2pose/posescript/utils.py#L268

* This part of the code determines the (randomized) order in which body parts should be described in the caption, then the (randomized) order in which descriptive pieces should be given, for each body part: https://github.com/naver/posescript/blob/f5282b1115ab09a077ba50a04b230a939306c604/src/text2pose/posescript/utils.py#L410-L415

**Note:** If your goal is to track semantic pose changes between poses in the same sequence, one way could be to:
1. compare the poses at the posecode level; eg. after this step: https://github.com/naver/posescript/blob/f5282b1115ab09a077ba50a04b230a939306c604/src/text2pose/posescript/captioning.py#L65 which outputs matrices, and does not involve randomization, as long as you comment this line:  https://github.com/naver/posescript/blob/f5282b1115ab09a077ba50a04b230a939306c604/src/text2pose/posescript/captioning.py#L286-L290
2. then to proceed with whatever kind of captioning you desire (while perhaps, keeping the randomization for a better effect), on the filtered codes of your choices (eg. on the ones that do not change over time; and/or separately, on the ones that do change).

Hope this helps!

**Comment by mkstmyk** [comment]
@g-delmas Thank you for your detailed and prompt response! In addition to the modifications related to randomization, your proposal to compare poses at the posecode level is very informative. I will try it out immediately!
