### ISSUE TITLE
在运行您的caption代码时遇到了这样的问题 

### ISSUE THREAD

**Issue by qianshanwei** [naver/posescript#28]
(notepose) root@701863d9da33:/share/Phi-3/pretrained_models/posescript-main/src/text2pose# python generative_caption/demo_generative_caption.py -- --model_path /share/Phi-3/pretrained_models/modgen_CAtransfPFAHPP_dataPFAftPFH/seed1/checkpoint_best.pth
Traceback (most recent call last):
  File "generative_caption/demo_generative_caption.py", line 15, in <module>
    import text2pose.demo as demo
  File "/share/Phi-3/pretrained_models/posescript-main/src/text2pose/demo.py", line 23, in <module>
    from human_body_prior.body_model.body_model import BodyModel
ModuleNotFoundError: No module named 'human_body_prior'
这样的报错是什么原因呢 似乎源代码中没有这样的模块：human_body_prior.body_model.body_model import BodyModel

**Comment by g-delmas** [comment]
Hello,

This package is automatically installed when you follow the setup process indicated in the README.md:
```bash
pip install -r requirements.txt
```
Indeed:
 https://github.com/naver/posescript/blob/f5282b1115ab09a077ba50a04b230a939306c604/requirements.txt#L7

Also please ask your questions about this repo in English in the future, thanks :slightly_smiling_face:.
