### ISSUE TITLE
Estimate Rotation and Translation

### ISSUE THREAD

**Issue by yufu-liu** [naver/posescript#4]
Hi, thanks for this amazing work.

Now that It is able to use text data and AMASS dataset to train a model for synthesizing new pose data via text description.
I am wondering that is it possible to generate rotation and translation data of pose via text data? 

Maybe can I train text data with rotation and translation data from AMASS dataset for a new model? Or use your model to generate pose image and rotation & translation?

**Comment by g-delmas** [comment]
Hi,

In our code & models, the global rotation is "normalized" so the pose would face front in all cases; and we don't use the translation. We used the same setting to collect the annotations for PoseScript, hence the annotations do not carry any information about the global rotation nor the translation. You cannot generate rotated & translated poses from text input using our model, in the current state.

Now, I can see two options for you:

**Option 1: plugging rotation & translation info.**
This (maybe easier) option could work if you are just interested in the generated data, and if it's simple to parse rotation & translation information in your texts.

1. remove any mention to the global rotation & translation in your text, if any
2. use our model for text-to-pose generation (no rotation & no translation info)
3. add the rotation & translation data to the generated parameters (this could be done automatically if you know by how many degrees to rotate the body & how many meters to translate the pose)
4. add back any mention of global rotation & translation in your text

**Option 2: training with rotation & translation.**
This option could work if you are essentially interested in the resulting model.

1. modify the automatic captioning pipeline to integrate rotation & translation information in the automatically generated texts (ie. define thresholds on rotations/translation values, categories, template sentences etc... to produce pieces of descriptions like "they are turned slightly to the right"/"they are turned to the right about 30°"/"they are 3 meters away" and so on)
2. generate new automatic data with rotation & translation information
3. modify the code so the model can take the original (not normalized) rotation & translation as input & output
4. train a new model on your customized automatic data

Beware that human-written annotations in PoseScript do not carry rotation & translation information! If you want to train on such data (eg. using the original global orientation & translation in AMASS), you would need to add one sentence to the descriptions mentioning rotation & translation requirements. Perhaps this can be done automatically (see option 2 > step 1).

**Comment by yufu-liu** [comment]
Thanks to your quick and detailed reply!

I found a similar project called "TEACH", and their code seems to be able to output the rotation and translation. I will try it first.
If the result/error compared to ground truth (AMASS dataset) is not good, I will come back to try these two methods. 

Really appreciate your help!

**Comment by g-delmas** [comment]
Indeed, changes in global rotation and translation are more meaningful for sequences (as with TEACH) than for single static poses (as here with PoseScript).

Good luck!
