### ISSUE TITLE
Missing Posecodes

### ISSUE THREAD

**Issue by pjyazdian** [naver/posescript#5]
Hi there,

First of all, thank you for your excellent work and well-written code. While working with your code, I came across a potential issue in the "aggreg_fbp_intptt_based" function.

In the `captioning.py` file, on line 1109, you have the following code: 

` if random.random() < PROP_AGGREGATION_HAPPENS: ` while PROP_AGGREGATION_HAPPENS is preset to 0.95.

This code means there's a slight chance that an aggregation, which is already picked and placed in aggregates_to_perform, might not occur. In such a case, the corresponding pose indices remain in the "unavailable_p_inds" list from the previous step ( making the aggregate_to_perfom list) and won't be added to the updated_posecodes list on line 1132:

`updated_posecodes.extend([p for p_ind, p in enumerate(posecodes_1p) if p_ind not in unavailable_p_inds])`.

I'd appreciate your thoughts on this special case.

Thank you in advance,

Payam

**Comment by g-delmas** [comment]
Hello Payam,

You are right, thanks for noticing this!

If aggregation does not happen, the related posecodes should be added back to the pool of non-to-be-aggregated posecodes, which are added to `updated_posecodes` at the end. This can be done by removing the indices of those posecodes from `unavailable_p_inds`.
It should now be solved :smile:!

**Comment by pjyazdian** [comment]
Thank you for your prompt response and resolving it.
