### ISSUE TITLE
Raise ValueError during evalution of generation reuslt

### ISSUE THREAD

**Issue by linjing7** [naver/posescript#6]
Hi, thanks for your excellent work and well-organized code! I met the following value error during my evaluation of the text2pose generation result:
```
File "posescript-main/src/text2pose/utils.py", line 81, in calculate_frechet_distance
    raise ValueError('Imaginary component {}'.format(m))
ValueError: Imaginary component 4.95291985246264e+23
```
I download your pretrained models and run the following script: `bash generative/script_generative.sh -a eval -c gen_glovebigru_vocA1H1_dataA1`.  Do you have any idea about this problem?

**Comment by g-delmas** [comment]
Hi !

Unfortunately, I could not reproduce this error.
The function actually comes from another code repo, you can see [here](https://github.com/mseitzer/pytorch-fid/issues?q=Imaginary) how some people have solved the problem.

It seems like one cause could be the version of scipy of your environment. I'm using version 1.10.1 and it works fine.

**Comment by linjing7** [comment]
Hi, thanks for your kind reply! It's indeed the problem caused by the scipy version. It works now and I can successfully reproduce your result.
