### ISSUE TITLE
Coordinate Transform

### ISSUE THREAD

**Issue by linjing7** [naver/posescript#7]
Hi, thanks for your great work!

I want to visualize the meshes generated by PoseScript with pyrender. However, I noticed that the visualization is unsatisfactory due to the coordinate inconsistency.  Below are the coordinates of PoseScript and Pyrender, respectively. Could you please tell me how can we transform PoseScript's coordinates into Pyrender's coordinates? I guess we could rotate the global orientation of SMPL parameters along x-axis by 90 degree or the output vertices directly.

<img width="891" alt="image" src="https://github.com/naver/posescript/assets/70081899/cc17cf8e-0f34-4338-8324-2d67684a60e9">

 

Thank you very much!

**Comment by g-delmas** [comment]
Hi!

OK, the edited version of your message makes much more sense to me :smile:
Yes, indeed, you need to **rotate the mesh around the x-axis by (minus) -90 degrees**, so to see the person in a front view and have the same reference frame as Pyrender. We do the following transformation in our visualization process:
https://github.com/naver/posescript/blob/4b46cdb58ed682db68015a3d447619f18ccdb316/src/text2pose/utils_visu.py#L173
You can also just apply this rotation to the vertices or coordinates. For example, we apply it on the coordinates inferred from the body model here:
https://github.com/naver/posescript/blob/4b46cdb58ed682db68015a3d447619f18ccdb316/src/text2pose/posescript/compute_coords.py#L64

You don't need to do this if you don't provide the root rotations to the body model. This comes from how the AMASS data is stored (you can check the section "Visualizing the global root orientation" in [this tutorial notebook](https://github.com/nghorbani/amass/blob/master/notebooks/01-AMASS_Visualization.ipynb)).

**Comment by linjing7** [comment]
Okay! Thanks for your kind reply! Your work is really nice and solid!
